### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by GregGoldman** [GregGoldman/BlinkLight#11]
Milestone 4 ready for review. See notes in release about odd formatting of this repository (temporary until I get me normal computer back).

**Comment by GregGoldman** [comment]
Added sphaerobolus as a collaborator. Awaiting response to assign to this issue

**Comment by mlp6** [comment]
Looks efficient... not surprised.

**Comment by mlp6** [comment]
@sphaerobolus for final signoff

**Comment by sphaerobolus** [comment]
Looks good to me!

We might even be able to etch this in house, if we're super duper careful.
