### ISSUE TITLE
Design 3d model draft of housing

### ISSUE THREAD

**Issue by GregGoldman** [GregGoldman/BlinkLight#7]

**Comment by ps178** [comment]
Could you clearly label your final CAD design that needs to be reviewed :) you have a lot of files under Mechanical

**Comment by GregGoldman** [comment]
Yes, sorry about that! It seems to have split my PCB into a bunch of parts and crowded that folder. 

It should be HousingTop.SLDPRT, HousingBottom.SLDPRT, BlinkLight_NewBat.SLDASM, and BlinkLight_NewBat.SLDDRW.
'first cad.PNG' is a screen clipping of the design all together
